<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../GistHub/Models/DownloaderModels.cs" Link="Models/DownloaderModels.cs" />
  </ItemGroup>
</Project>
